### ISSUE TITLE
[Bug] Display Melonprefs Tab toggle duplicates menus.

### ISSUE THREAD

**Issue by NotAKidoS** [BTK-Development/BTKUILib#1]
Toggling the Melonprefs Tab will duplicate the toggle and categories. Nuked my FPS into the ground.

https://youtu.be/XyTkA4mQBLI

**Comment by NotAKidoS** [comment]
The FPS hit was really noticable while unmuted. Confused why mute/unmute affected FPS that much.

**Comment by ddakebono** [comment]
Fixed in release [1.0.1](https://github.com/BTK-Development/BTKUILib/releases/tag/1.0.1)
