### ISSUE TITLE
OpenNumberInput with floats between 0 and 1 appends trailing zeros

### ISSUE THREAD

**Issue by Nirv-git** [BTK-Development/BTKUILib#11]
When using OpenNumberInput with floats between 0 and 1, the UI shows all the possible trailing zeros and is very hard to use, as you must backspace through all of them.

Example,
`QuickMenuAPI.OpenNumberInput("Custom Nearclip", 0.05f, (action) =>`
![image](https://user-images.githubusercontent.com/81605232/233196294-7b5e8f66-fb31-4f85-a29f-70decba0521f.png)

Works fine with others!
![image](https://user-images.githubusercontent.com/81605232/233199032-488851de-e336-4ce0-a8be-e3b5dc5e4ec3.png)

![image](https://user-images.githubusercontent.com/81605232/233199508-a06f8acf-5302-49c3-b252-2fc8d817a84f.png)

**Comment by ddakebono** [comment]
I've clamped the max decimal places to 3 in 1.2.0-preview2, this should hopefully resolve the issue here.
