### ISSUE TITLE
[Feature Request] Images functions to help with caching

### ISSUE THREAD

**Issue by kafeijao** [BTK-Development/BTKUILib#12]
API to allow:
- Check if image already exists in BKTUI (so we can cache stuff instead of getting from the API across game restarts)
- Clear all images for a mod (when I'm caching stuff like world/avatar icons, removing all icons to clear the cache might be useful)

**Comment by ddakebono** [comment]
I've added QuickMenuAPI.DoesIconExist in 1.2.0-preview2, as for clearing all icons from a mod, I don't think this is something I would implement here as it would be all or nothing, if a path is required to clear a certain part the mod itself might as well do it internally.
