### ISSUE TITLE
Players in World selection menu header shows last openned page

### ISSUE THREAD

**Issue by Nirv-git** [BTK-Development/BTKUILib#3]
The Players in World selection menu on the right of the Quick Menu will show the header text for the last opened page.

Here is an example, I just went to each page, then back to player select, and the header doesn't clear

![image](https://user-images.githubusercontent.com/81605232/219225153-ef5a54c2-ab1f-4962-97cb-7690eb57141b.png)

**Comment by ddakebono** [comment]
Yea, this has been a known thing for a bit, I'd meant to fix it up when I did the next chunk of work to it

**Comment by ddakebono** [comment]
"fixed" in 1.2.0-preview1, I just made the select page bigger. The header is totally gone don't worry about it
