### ISSUE TITLE
[Feature Request] Icons Stuff

### ISSUE THREAD

**Issue by kafeijao** [BTK-Development/BTKUILib#4]
Not sure if already requested, planned, or even implemented (I might've failed to find these ;_;)

- Buttons (and maybe other components) without an icon. Sometimes I got a long text and it gets pushed down because the icon is taking most of the space.
- Allow URLs for the icons, or maybe just cvr entities, or maybe both xD. So for example if I want to display a world/player image on a component I can.
- Allow to force update an icon or clear our mod's cached icons (useful when we do an update and we changed an icon)

**__Edit__**: Oooooh I forgot one
- Allow the icons in buttons to be on the background, so the button text is in front of the image

**Comment by ddakebono** [comment]
Most of these changes have been implemented in 1.2.0-preview1, the only thing that hasn't is URLs for icons, still gotta decide a way to handle that nicely

**Comment by ddakebono** [comment]
URL support is now in for 1.2.0-preview2, note that it only allows icons to be pulled from https://files.abidata.io
