### ISSUE TITLE
[Bug] Button Update when icon empty goes brrrr

### ISSUE THREAD

**Issue by kafeijao** [BTK-Development/BTKUILib#8]
![image](https://user-images.githubusercontent.com/4409693/228084984-f2710a39-24e0-44be-b051-4ee0fa6ae50a.png)
![image](https://user-images.githubusercontent.com/4409693/228085010-1cd2c570-ab69-4a1d-83c3-f70f59a6c67e.png)
![image](https://user-images.githubusercontent.com/4409693/228085256-c6ffc181-e62e-4dc6-be91-8832b93b0eb0.png)
![image](https://user-images.githubusercontent.com/4409693/228085331-9c934501-90ac-406a-a192-ddfdc0d357c1.png)

**It seems that when I try to update a button's text when the icon is `""` it will nono**

**Comment by kafeijao** [comment]
ooh I think I found the issue

https://github.com/BTK-Development/BTKUILib/blob/c23f867d60a8b841de4b8ebd6eef06140efbfc1d/UIObjects/Components/Button.cs#L100

I think it's missing ` + "-Image"` apended to the `ElementID` on the icon update

**Comment by ddakebono** [comment]
This bug should be fixed in 1.2.0-preview1, give it a go in that version.
